---
# tasks file for install-web-and-db-server
- name: Start the Docker
  become: yes
  service:
    name: docker
    state: started
    enabled: yes

- name: Use docker service to install web server
  become: yes
  docker_image:
    name: romeoz/docker-apache-php
    state: present
    source: pull

- name: Use docker service to install db server
  become: yes
  docker_image:
    name: mysql/mysql-server:latest
    state: present
    source: pull

