---
# tasks file for install-docker-centos
- name: Install pre-requisites for Docker
  yum:
    name:
      - python3
      - python3-pip
    state: latest
  when: ansible_distribution == "CentOS"

- name: Download dependencies
  command: "sudo yum install -y yum-utils device-mapper-persistent-data lvm2"

- name: Install Docker
  yum:
    name: docker
    state: latest
    update_cache: yes
  register: docker
  when: ansible_distribution == "CentOS"

- name: Install docker.py
  pip: 
    name: docker.py
    state: latest
  when: docker.changed
        
